\set ON_ERROR_STOP on
BEGIN;
DO $$
DECLARE owner uuid; other_owner uuid; sc uuid; character uuid; story uuid; job uuid; lease uuid:=gen_random_uuid(); result jsonb; before_balance integer; after_balance integer; target uuid;
BEGIN
 result:=web_login(jsonb_build_object('identity',jsonb_build_object('provider','google','issuer','https://accounts.google.com','subject','test-user','display_name','Test'),'flow','{}'::jsonb,'token_hash','test-token','csrf','test-csrf'));
 owner:=(result->>'user_id')::uuid;
 IF owner IS NULL THEN RAISE EXCEPTION 'Login failed: %',result; END IF;
 SELECT balance INTO before_balance FROM credit_balances WHERE user_id=owner;
 PERFORM web_login(jsonb_build_object('identity',jsonb_build_object('provider','google','issuer','https://accounts.google.com','subject','test-user','display_name','Test'),'flow','{}'::jsonb,'token_hash','test-token-2','csrf','test-csrf-2'));
 SELECT balance INTO after_balance FROM credit_balances WHERE user_id=owner;
 IF before_balance<>after_balance THEN RAISE EXCEPTION 'Welcome granted twice'; END IF;

 result:=web_login(jsonb_build_object('identity',jsonb_build_object('provider','google','issuer','https://accounts.google.com','subject','blocked-new','display_name','Test'),'flow','{}'::jsonb,'token_hash','blocked-token','csrf','c','allow_registration',false));
 IF result->>'error' IS DISTINCT FROM 'ADMISSIONS_DISABLED' THEN RAISE EXCEPTION 'Rollback admitted new account'; END IF;
 result:=web_login(jsonb_build_object('identity',jsonb_build_object('provider','google','issuer','https://accounts.google.com','subject','test-user','display_name','Test'),'flow','{}'::jsonb,'token_hash','existing-rollback','csrf','c','allow_registration',false));
 IF (result->>'user_id')::uuid IS DISTINCT FROM owner THEN RAISE EXCEPTION 'Rollback blocked existing login'; END IF;
 result:=web_login(jsonb_build_object('identity',jsonb_build_object('provider','line','issuer','https://access.line.me','subject','test-line','display_name','Test'),'flow','{}'::jsonb,'token_hash','line-token','csrf','c'));
 other_owner:=(result->>'user_id')::uuid;
 result:=web_login(jsonb_build_object('identity',jsonb_build_object('provider','line','issuer','https://access.line.me','subject','test-line','display_name','Test'),'flow',jsonb_build_object('link_user_id',owner,'link_session_hash','test-token'),'token_hash','conflict-token','csrf','c'));
 IF result->>'error' IS DISTINCT FROM 'IDENTITY_ALREADY_LINKED' THEN RAISE EXCEPTION 'Identity conflict merged accounts'; END IF;
 IF (SELECT user_id FROM auth_identities WHERE provider='line' AND subject='test-line') IS DISTINCT FROM other_owner THEN RAISE EXCEPTION 'Identity owner changed'; END IF;
 INSERT INTO characters(name,personality,speaking_style,background,system_prompt,gender) VALUES('Test','Test','Test','Test','SECRET','female') RETURNING id INTO character;
 INSERT INTO scenes(character_id,name,location,time_of_day,atmosphere,situation_prompt,opening_narrator,opening_dialogue) VALUES(character,'Test','Test','Test','Test','PRIVATE','Opening','Hello') RETURNING id INTO sc;
 IF web_scene(sc)::text LIKE '%SECRET%' OR web_scene(sc)::text LIKE '%PRIVATE%' THEN RAISE EXCEPTION 'Prompt leaked'; END IF;
 UPDATE users SET terms_accepted_at=now() WHERE id=owner;
 result:=web_mutate_story(owner,'create',jsonb_build_object('scene_id',sc,'persona',jsonb_build_object('name','Reader','description','')),'create-1');
 story:=(result->>'id')::uuid;
 IF story IS NULL THEN RAISE EXCEPTION 'Create failed: %',result; END IF;
 IF web_story(gen_random_uuid(),story) IS NOT NULL THEN RAISE EXCEPTION 'Cross-user read'; END IF;
 result:=admit_turn(owner,story,'web','turn','turn-1',jsonb_build_object('content','Hello','expected_version',0));
 job:=(result->>'id')::uuid;
 IF job IS NULL THEN RAISE EXCEPTION 'Admission failed: %',result; END IF;
 result:=admit_turn(owner,story,'web','turn','turn-1',jsonb_build_object('content','Hello','expected_version',0));
 IF (result->>'id')::uuid<>job THEN RAISE EXCEPTION 'Duplicate job'; END IF;
 result:=admit_turn(owner,story,'web','turn','turn-1',jsonb_build_object('content','Different','expected_version',0));
 IF result->>'error' IS DISTINCT FROM 'IDEMPOTENCY_MISMATCH' THEN RAISE EXCEPTION 'Mismatched key allowed'; END IF;
 result:=admit_turn(owner,story,'web','turn','turn-2',jsonb_build_object('content','Hello','expected_version',0));
 IF result->>'error' IS DISTINCT FROM 'TURN_IN_PROGRESS' THEN RAISE EXCEPTION 'Second generation allowed'; END IF;

 result:=web_mutate_story(owner,'persona',jsonb_build_object('session_id',story,'expected_version',0,'persona',jsonb_build_object('name','Changed','description','')),'');
 IF result->>'error' IS DISTINCT FROM 'TURN_IN_PROGRESS' THEN RAISE EXCEPTION 'Persona changed during generation'; END IF;
 UPDATE jobs SET status='processing',lease_token=lease,lease_expires_at=now()+interval '5 minutes' WHERE id=job;
 result:=settle_turn(job,gen_random_uuid(),jsonb_build_object('content','Must not save'));
 IF result->>'error' IS DISTINCT FROM 'STALE_LEASE' THEN RAISE EXCEPTION 'Stale worker allowed'; END IF;
 result:=settle_turn(job,lease,jsonb_build_object('content','*Smile* Hello','mood','happy'));
 target:=(result->>'message_id')::uuid;
 IF target IS NULL THEN RAISE EXCEPTION 'Settlement failed: %',result; END IF;
 PERFORM settle_turn(job,lease,jsonb_build_object('content','Must not replace'));
 IF (SELECT count(*) FROM credit_transactions WHERE reference_id=job)<>1 THEN RAISE EXCEPTION 'Duplicate debit'; END IF;
 IF (SELECT content FROM messages WHERE id=target)<>'*Smile* Hello' THEN RAISE EXCEPTION 'Replay changed answer'; END IF;
 IF (SELECT message_count FROM roleplay_sessions WHERE id=story)<>1 THEN RAISE EXCEPTION 'Unexpected user count'; END IF;
 SELECT balance-reserved INTO before_balance FROM credit_balances WHERE user_id=owner;
 result:=admit_turn(owner,story,'web','regeneration','regen-1',jsonb_build_object('message_id',target,'expected_version',1));
 IF result->>'error' IS DISTINCT FROM 'VALIDATION_ERROR' THEN RAISE EXCEPTION 'Regeneration admitted: %',result; END IF;
 SELECT balance-reserved INTO after_balance FROM credit_balances WHERE user_id=owner;
 IF before_balance<>after_balance OR EXISTS(SELECT 1 FROM jobs WHERE user_id=owner AND request_key='regen-1') THEN RAISE EXCEPTION 'Rejected regeneration reserved credit'; END IF;
 result:=admit_turn(owner,story,'web','turn','fail-1',jsonb_build_object('content','Hello','expected_version',1));
 job:=(result->>'id')::uuid;
 UPDATE jobs SET status='processing',lease_token=lease,lease_expires_at=now()+interval '5 minutes' WHERE id=job;
 PERFORM fail_turn(job,lease); PERFORM fail_turn(job,lease);
 IF (SELECT reserved FROM credit_balances WHERE user_id=owner)<>0 THEN RAISE EXCEPTION 'Reservation leaked'; END IF;
 IF (SELECT count(*) FROM credit_grants WHERE user_id=owner AND grant_kind='daily')<>1 THEN RAISE EXCEPTION 'Daily granted twice'; END IF;
 INSERT INTO roleplay_sessions(user_id,character_id,scene_id,interaction_channel) VALUES(owner,character,sc,'line') RETURNING id INTO story;
 INSERT INTO messages(session_id,role,content) VALUES(story,'character','Legacy opening') RETURNING id INTO target;
 result:=admit_turn(owner,story,'web','turn','shared-web',jsonb_build_object('content','From web','expected_version',0));
 job:=(result->>'id')::uuid;
 IF job IS NULL THEN RAISE EXCEPTION 'Web turn on LINE story failed: %',result; END IF;
 result:=admit_turn(owner,story,'line','turn','shared-line-busy',jsonb_build_object('content','From LINE'));
 IF result->>'error' IS DISTINCT FROM 'TURN_IN_PROGRESS_ELSEWHERE' THEN RAISE EXCEPTION 'Cross-surface admit on busy story: %',result; END IF;
 result:=admit_turn(owner,story,'web','turn','shared-web-busy',jsonb_build_object('content','Again','expected_version',0));
 IF result->>'error' IS DISTINCT FROM 'TURN_IN_PROGRESS' THEN RAISE EXCEPTION 'Same-surface admit on busy story: %',result; END IF;
 UPDATE jobs SET status='processing',lease_token=lease,lease_expires_at=now()+interval '5 minutes' WHERE id=job;
 PERFORM settle_turn(job,lease,jsonb_build_object('content','*Nod* Hi','mood','happy'));
 result:=admit_turn(owner,story,'line','turn','shared-line',jsonb_build_object('content','From LINE'));
 job:=(result->>'id')::uuid;
 IF job IS NULL THEN RAISE EXCEPTION 'LINE turn on LINE story failed: %',result; END IF;
 UPDATE jobs SET status='processing',lease_token=lease,lease_expires_at=now()+interval '5 minutes' WHERE id=job;
 PERFORM fail_turn(job,lease);
 IF (SELECT interaction_channel FROM roleplay_sessions WHERE id=story)<>'line' THEN RAISE EXCEPTION 'Web turn changed LINE selection'; END IF;
 result:=web_mutate_story(owner,'transfer',jsonb_build_object('session_id',story,'expected_version',0),'transfer-1');
 IF result->>'error' IS DISTINCT FROM 'NOT_FOUND' THEN RAISE EXCEPTION 'Transfer still available: %',result; END IF;
 IF (SELECT interaction_channel FROM roleplay_sessions WHERE id=story)<>'line' THEN RAISE EXCEPTION 'Retired transfer changed channel'; END IF;
 IF (SELECT content FROM messages WHERE id=target) IS DISTINCT FROM 'Legacy opening' THEN RAISE EXCEPTION 'History changed'; END IF;

END $$;
ROLLBACK;
